Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('m-files')->group(function() {
            
            Route::name('item.')->group(function() {
                Route::get('items/exports/{id}/{fID}', 'ItemsController@exportExcel')->name('byidfid.export');
                Route::get('items', 'ItemsController@index')->name('index');
                Route::get('items/{id}', 'ItemsController@getViewByID')->name('id');
                Route::get('items/object/{id}', 'ItemsController@getObjectByID')->name('object.byid');
                Route::get('items/prop/{id}', 'ItemsController@getPropertyDefDetail')->name('prop.id');
                Route::get('items/{id}/{fID}', 'ItemsController@getViewByIDfID')->name('byidfid');
                
                Route::get('items/sync/{id}/{fID}', 'ItemsController@syncByIDfID')->name('sync.byidfid');
            });

            Route::name('sertipikat.')->group(function() {
                Route::get('sertipikat', 'SertipikatController@index')->name('index');
                Route::get('sertipikat/data', 'SertipikatController@indexData')->name('index.data');
                Route::get('sertipikat/show', 'SertipikatController@show')->name('show');
                Route::get('sertipikat/sync', 'SertipikatController@sync')->name('sync');
                Route::get('sertipikat/sync-data', 'SertipikatController@syncDataNull')->name('sync.data');
                Route::get('sertipikat/export', 'SertipikatController@exportToExcel')->name('export');

                Route::get('sertipikat/search', 'SertipikatController@search')->name('search');
                Route::get('sertipikat/search/now', 'SertipikatController@searchNow')->name('search.now');
                Route::get('sertipikat/sync/now', 'SertipikatController@syncNow')->name('sync.now');
            });

            Route::name('warkah.')->group(function() {
                Route::get('warkah', 'WarkahController@index')->name('index');
                Route::get('warkah/data', 'WarkahController@indexData')->name('index.data');
                Route::get('warkah/show', 'WarkahController@show')->name('show');
                Route::get('warkah/sync', 'WarkahController@sync')->name('sync');
                Route::get('warkah/export', 'WarkahController@exportToExcel')->name('export');
            });

        });
    });
});

Entities/Warkah.php
<?php

namespace Modules\Mfiles\Entities;

use App\Models\User;
use App\Traits\Uuid as TraitsUuid;
use Illuminate\Database\Eloquent\Model;

class Warkah extends Model
{
    use TraitsUuid;

    protected $table = 'mfl_warkah';

    public $incrementing    = false;

    protected $dates = [
        'sph_dt',
        'created',
        'last_modified',
    ];

    protected $fillable = [
        'index',
        'kode',
        'nomor',
        'name',
        'jenis',
        'luas',
        'desa',
        'kecamatan',
        'kabupaten',
        'sph_no',
        'sph_nm',
        'sph_dt',
        'sph_ls',
        'ktp',
        'kk',
        'sk_sengketa',
        'sk_waris',
        'k_waris',
        'k_jual',
        'pbb',
        'created',
        'created_by',
        'last_modified',
        'last_modified_by',
        'last_sync',
        'last_sync_by',
        'doc_id',
        'doc_title',
        'doc_version',
        'doc_type',
        'file_size',
        'file_ext',
    ];

    public function lastSyncBy()
    {
        return $this->belongsTo(User::class, 'last_sync_by')->withDefault([
            'name' => null
        ]);
    }
}

Http/Controllers/WarkahController.php
<?php

namespace Modules\Mfiles\Http\Controllers;

use Exception;
use Carbon\Carbon;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Mfiles\Entities\Warkah;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;
use Modules\Mfiles\Exports\WarkahExportToExcel;

class WarkahController extends Controller
{
    protected $pageTitle;
    protected $baseUrl;
    protected $username;
    protected $password;
    protected $vaultID;

    protected $client;
    protected $headers;

    public function __construct()
    {
        $this->pageTitle = 'Warkah';
        $this->baseUrl      = config('mfiles.base_url');
        $this->username     = config('mfiles.username');
        $this->password     = config('mfiles.password');
        $this->vaultID      = config('mfiles.vault_id');

        $this->client       = new Client();
        $this->headers      = [
            'Accept'        => 'application/json',
            'X-Username'    => $this->username,
            'X-Password'    => $this->password,
            'X-Vault'       => $this->vaultID
        ];
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('mfiles::warkah.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {
            $data = new Warkah();
            $data = $data->orderBy('last_modified', 'desc');
            $data = $data->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row) {
                    $actionBtn = 
                    '
                        <div class="btn-group">
                            <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Action</span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                <li>
                                    <a href="#" onclick="showDetail(\''.$row->id.'\');return false;"><i class="fa fa-eye"></i> Detail</a>
                                </li>
                            </ul>
                        </div>
                    ';
                    return $actionBtn;
                })
                ->rawColumns([
                    'action'
                ])
                ->make(true);
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show(Request $request)
    {
        $params['title']    = $this->pageTitle;
        $params['data']     = Warkah::findOrFail($request->id);
        return view('mfiles::warkah.show', $params);
    }

    public function sync()
    {
        try {

            ini_set('memory_limit','256M');
            ini_set('max_execution_time','0');
            $endPoint   = $this->baseUrl . 'views/V101/L9/items?limit=20000';
            $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
            $result         = json_decode($response->getbody()->getContents(), true);
            
            foreach($result['Items'] as $item) {
                if($item['FolderContentItemType'] == 4) {
                    $data['docTitle']   = $item['ObjectVersion']['Title'];
                    $data['docLastModUtc']  = $item['ObjectVersion']['LastModifiedUtc'];
                    $data['docID']      = $docID        = $item['ObjectVersion']['ObjVer']['ID'];
                    $data['docVersion'] = $docVersion   = $item['ObjectVersion']['ObjVer']['Version'];
                    $data['docType']    = $docType      = $item['ObjectVersion']['ObjVer']['Type'];
                    $data['fileSize']   = $item['ObjectVersion']['Files'][0]['Size'];
                    $data['fileExt']    = $item['ObjectVersion']['Files'][0]['Extension'];

                    $data['docProperties']  = array_reduce($this->getDocumentProperties($docType, $docID, $docVersion), 'array_merge', []);

                    if($data['docProperties']['supportingDocumentType'] == 'Warkah') {
                        $dataWrkh['doc_id']     = $data['docID'];
                        $dataWrkh['doc_title']  = $data['docTitle'];
                        $dataWrkh['doc_version']= $data['docVersion'];
                        $dataWrkh['doc_type']   = $data['docType'];
                        $dataWrkh['file_size']  = $data['fileSize'];
                        $dataWrkh['file_ext']   = $data['fileExt'];

                        $dataWrkh['nomor']      = $data['docProperties']['nomorDokumen'];
                        $dataWrkh['name']       = $data['docProperties']['subjectName'];
                        $dataWrkh['jenis']      = $data['docProperties']['jenisDokumen'];
                        $dataWrkh['luas']       = (double) cleanNominal($data['docProperties']['luasDokumen']);
                        $dataWrkh['desa']       = capitalize($data['docProperties']['desa']);
                        $dataWrkh['kecamatan']  = capitalize($data['docProperties']['kecamatan']);
                        $dataWrkh['kabupaten']  = capitalize($data['docProperties']['kabupaten']);
                        $dataWrkh['sph_no']     = $data['docProperties']['nomorSPH'];
                        $dataWrkh['sph_nm']     = $data['docProperties']['namaSPH'];
                        $dataWrkh['sph_dt']     = dateFormatYmd($data['docProperties']['tanggalSPH']);
                        $dataWrkh['sph_ls']     = (double) cleanNominal($data['docProperties']['luasSPH']);
                        $dataWrkh['ktp']        = $this->convertState($data['docProperties']['kTP']);
                        $dataWrkh['kk']         = $this->convertState($data['docProperties']['kartuKeluarga']);
                        $dataWrkh['sk_sengketa']= $this->convertState($data['docProperties']['suratKeteranganSengketa']);
                        $dataWrkh['sk_waris']   = $this->convertState($data['docProperties']['suratKeteranganWaris']);
                        $dataWrkh['k_waris']    = $this->convertState($data['docProperties']['kuasaWaris']);
                        $dataWrkh['k_jual']     = $this->convertState($data['docProperties']['kuasaJual']);
                        $dataWrkh['pbb']        = $this->convertState($data['docProperties']['pBB']);

                        $dataWrkh['last_sync']  = Carbon::now();
                        $dataWrkh['last_sync_by']= Auth::user()->id;
                        $dataWrkh['created']    = dateFormatYmdHis($data['docProperties']['created']);
                        $dataWrkh['created_by'] = $data['docProperties']['createdBy'];
                        $dataWrkh['last_modified']= dateFormatYmdHis($data['docProperties']['lastModified']);
                        $dataWrkh['last_modified_by'] = $data['docProperties']['lastModifiedBy'];

                        $cekWrkhExist = Warkah::where('doc_id', $data['docID']);
                
                        if($cekWrkhExist->count() > 0) {
                            $lastModified = dateFormatYmdHis($data['docProperties']['lastModified']);
                            if($cekWrkhExist->where('last_modified', '!=', $lastModified)->count() > 0) {
                                $cekWrkhExist->update($dataWrkh);
                            }
                        } else {
                            Warkah::create($dataWrkh);
                        }
                    }
                }
            }

            return response()->json([
                'message' => trans('message.success_save')
            ]);

        } catch(Exception $e) {

            return response()->json([
                'message' => trans('message.error_save')
            ]);
        }
    }

    public function exportToExcel()
    {
        
        $data = Warkah::orderBy('last_modified', 'desc')->get();

        return Excel::download(new WarkahExportToExcel($data), 'warkah_'.date('Y-m-d').'.xlsx');
        
    }

    private function getDocumentProperties($type, $id, $version) {
        $endPoint   = $this->baseUrl . 'objects/properties;' . $type . '/' . $id . '/' . $version;
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result     = json_decode($response->getbody()->getContents(), true);
        $resultArray= [];
        foreach($result[0] as $item) {
            $arrayData = array(
                camel_case($this->getPropertyDefDetail($item['PropertyDef'])) => $item['Value']['DisplayValue']
            );
            array_push($resultArray, $arrayData);
        }
        return array_merge($resultArray);
    }

    private function getPropertyDefDetail($id) {
        $endPoint   = $this->baseUrl . 'structure/properties/' . $id;
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        return $result['Name'];
    }

    private function convertState($state)
    {
        switch ($state) {
            case 'Ada':
                $result = true;
                break;
            case 'Tidak Ada':
                $result = false;
                break;
            default:
                $result = false;
                break;
        }

        return $result;
    }

}

Resources/views/warkah/index.blade.php
@extends('mfiles::layouts.master')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        @can('mfiles-warkah-sync')
                            <a class="btn btn-sm btn-info" id="btn-sync">
                                <i class="fa fa-refresh"></i> Sync
                            </a>
                        @endcan
                        @can('mfiles-warkah-export')
                            <a class="btn btn-sm btn-success" href="{!! route('warkah.export') !!}">
                                <i class="fa fa-file-excel-o"></i> Export to Excel
                            </a>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 500px">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="grid-warkah" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="vertical-align: middle; width: 2%">#</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Nomor</th>
                                        <th class="text-center" style="vertical-align: middle;">Nama</th>
                                        <th class="text-center" style="vertical-align: middle; width: 10%">Jenis</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Luas (m<sup>2</sup>)</th>
                                        <th class="text-center" style="vertical-align: middle; width: 10%">Desa</th>
                                        <th class="text-center" style="vertical-align: middle; width: 10%">Kabupaten</th>
                                        <th class="text-center" style="vertical-align: middle; width: 100px">Modified</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">
                                            <i class="fa fa-navicon"></i>
                                        </th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="form-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="detail">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div id="content"></div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            var btnSync = $('#btn-sync');
            @can('mfiles-warkah-sync')
            btnSync.on('click', function(e) {
                btnSync.attr('disabled', true);
                $.ajax({
                    url: "{!! route('warkah.sync') !!}",
                    type: "GET",
                    success: function(data) {
                        toastr.success(data.message);
                        $('#grid-warkah').DataTable().ajax.reload(null, false);
                        btnSync.attr('disabled', false);
                    },
                    error: function(error) {
                        toastr.error(error.message);
                        btnSync.attr('disabled', false);
                    }
                });
            });
            @endcan

            var table = $('#grid-warkah').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload(null, false);
                        }
                    },
                ],
                ajax: { 
                    url: "{!! route('warkah.index.data') !!}",
                    pages: 10,
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'nomor', name: 'nomor', className: "small"},
                    {data: 'name', name: 'name', className: "small"},
                    {data: 'jenis', name: 'jenis', className: "small"},
                    {data: 'luas', name: 'luas', className: "small text-right"},
                    {data: 'desa', name: 'desa', className: "small"},
                    {data: 'kabupaten', name: 'kabupaten', className: "small"},
                    {data: 'last_modified', name: 'last_modified', className: "small"},
                    {data: 'action', name: 'action', className: "small text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 4, render: $.fn.dataTable.render.number( '.', ',', 0, '' )},
                    {targets: 7, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm' )},
                ],
                order: [
                    [7, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });
        });

        function showDetail(id) {
            $.ajax({
                type: "GET",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{!! route('warkah.show') !!}",
                data: {id: id},
                success: function(data) {
                    $('#form-modal').modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                    $('#content').html(data);
                }
            });
        }

    </script>
@endsection

Resources/views/warkah/show.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="detail">Detail {!! $title !!}</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-6">
            <table class="table table-condensed table-striped">
                <tbody>
                    <tr>
                        <th style="width: 40%">Nomor</th>
                        <td>{!! $data->nomor !!}</td>
                    </tr>
                    <tr>
                        <th>Nama</th>
                        <td>{!! $data->name !!}</td>
                    </tr>
                    <tr>
                        <th>Jenis Dokumen</th>
                        <td>{!! $data->jenis !!}</td>
                    </tr>
                    <tr>
                        <th>Luas</th>
                        <td>{!! numberFormat($data->luas) !!} m<sup>2</sup></td>
                    </tr>
                    <tr>
                        <th>Desa</th>
                        <td>{!! $data->desa !!}</td>
                    </tr>
                    <tr>
                        <th>Kecamatan</th>
                        <td>{!! $data->kecamatan !!}</td>
                    </tr>
                    <tr>
                        <th>Kabupaten</th>
                        <td>{!! $data->kabupaten !!}</td>
                    </tr>
                    <tr>
                        <th>Nomor SPH</th>
                        <td>{!! $data->sph_no !!}</td>
                    </tr>
                    <tr>
                        <th>Nama SPH</th>
                        <td>{!! $data->sph_nm !!}</td>
                    </tr>
                    <tr>
                        <th>Tgl. SPH</th>
                        <td>{!! dateFormatDmy($data->sph_dt) !!}</td>
                    </tr>
                    <tr>
                        <th>Luas SPH</th>
                        <td>{!! numberFormat($data->sph_ls) !!} m<sup>2</sup></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-condensed table-striped">
                <tbody>
                    <tr>
                        <th style="width: 60%">KTP</th>
                        <td>{!! __getStateDetail($data->ktp) !!}</td>
                    </tr>
                    <tr>
                        <th>KK</th>
                        <td>{!! __getStateDetail($data->kk) !!}</td>
                    </tr>
                    <tr>
                        <th>Surat Keterangan Sengketa</th>
                        <td>{!! __getStateDetail($data->sk_sengketa) !!}</td>
                    </tr>
                    <tr>
                        <th>Surat Keterangan Waris</th>
                        <td>{!! __getStateDetail($data->sk_waris) !!}</td>
                    </tr>
                    <tr>
                        <th>Kuasa Waris</th>
                        <td>{!! __getStateDetail($data->k_waris) !!}</td>
                    </tr>
                    <tr>
                        <th>Kuasa Jual</th>
                        <td>{!! __getStateDetail($data->k_jual) !!}</td>
                    </tr>
                    <tr>
                        <th>PBB</th>
                        <td>{!! __getStateDetail($data->pbb) !!}</td>
                    </tr>
                    <tr>
                        <th></th>
                        <td></td>
                    </tr>
                    <tr>
                        <th>Created</th>
                        <td>{!! dateFormatDmyHi($data->created) !!} WIB</td>
                    </tr>
                    <tr>
                        <th>Created By</th>
                        <td>{!! capitalize($data->created_by) !!}</td>
                    </tr>
                    <tr>
                        <th>Last Modified</th>
                        <td>{!! dateFormatDmyHi($data->last_modified) !!} WIB</td>
                    </tr>
                    <tr>
                        <th>Last Modified By</th>
                        <td>{!! capitalize($data->last_modified_by) !!}</td>
                    </tr>
                    <tr>
                        <th>Last Sync</th>
                        <td>{!! dateFormatDmyHi($data->last_sync) !!} WIB</td>
                    </tr>
                    <tr>
                        <th>Last Sync By</th>
                        <td>{!! capitalize($data->lastSyncBy->name) !!}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal-footer">

</div>