Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('m-files')->group(function() {
            
            Route::name('item.')->group(function() {
                Route::get('items/exports/{id}/{fID}', 'ItemsController@exportExcel')->name('byidfid.export');
                Route::get('items', 'ItemsController@index')->name('index');
                Route::get('items/{id}', 'ItemsController@getViewByID')->name('id');
                Route::get('items/object/{id}', 'ItemsController@getObjectByID')->name('object.byid');
                Route::get('items/prop/{id}', 'ItemsController@getPropertyDefDetail')->name('prop.id');
                Route::get('items/{id}/{fID}', 'ItemsController@getViewByIDfID')->name('byidfid');
                
                Route::get('items/sync/{id}/{fID}', 'ItemsController@syncByIDfID')->name('sync.byidfid');
            });

            Route::name('sertipikat.')->group(function() {
                Route::get('sertipikat', 'SertipikatController@index')->name('index');
                Route::get('sertipikat/data', 'SertipikatController@indexData')->name('index.data');
                Route::get('sertipikat/show', 'SertipikatController@show')->name('show');
                Route::get('sertipikat/sync', 'SertipikatController@sync')->name('sync');
                Route::get('sertipikat/sync-data', 'SertipikatController@syncDataNull')->name('sync.data');
                Route::get('sertipikat/export', 'SertipikatController@exportToExcel')->name('export');

                Route::get('sertipikat/search', 'SertipikatController@search')->name('search');
                Route::get('sertipikat/search/now', 'SertipikatController@searchNow')->name('search.now');
                Route::get('sertipikat/sync/now', 'SertipikatController@syncNow')->name('sync.now');
            });

            Route::name('warkah.')->group(function() {
                Route::get('warkah', 'WarkahController@index')->name('index');
                Route::get('warkah/data', 'WarkahController@indexData')->name('index.data');
                Route::get('warkah/show', 'WarkahController@show')->name('show');
                Route::get('warkah/sync', 'WarkahController@sync')->name('sync');
                Route::get('warkah/export', 'WarkahController@exportToExcel')->name('export');
            });

        });
    });
});

Resources/views/admin/shared/sidebar.blade.php
@can('mfiles')
<li class="treeview @if($adminActiveMenu == 'm-files') active @endif">
    <a href="#">
        <i class="fa fa-file-text-o"></i>
        <span>M-Files</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        @can('mfiles-sertifikat-read')
            <li class="@if($adminActiveSubMenu == 'sertipikat') active @endif"><a href="{!! route('sertipikat.index') !!}"><i class="fa fa-circle-o"></i> Sertifikat</a></li>
        @endcan
        @can('mfiles-warkah-read')
            <li class="@if($adminActiveSubMenu == 'warkah') active @endif"><a href="{!! route('warkah.index') !!}"><i class="fa fa-circle-o"></i> Warkah</a></li>
        @endcan
    </ul>
</li>
@endcan