Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('m-files')->group(function() {
            
            Route::name('item.')->group(function() {
                Route::get('items/exports/{id}/{fID}', 'ItemsController@exportExcel')->name('byidfid.export');
                Route::get('items', 'ItemsController@index')->name('index');
                Route::get('items/{id}', 'ItemsController@getViewByID')->name('id');
                Route::get('items/object/{id}', 'ItemsController@getObjectByID')->name('object.byid');
                Route::get('items/prop/{id}', 'ItemsController@getPropertyDefDetail')->name('prop.id');
                Route::get('items/{id}/{fID}', 'ItemsController@getViewByIDfID')->name('byidfid');
                
                Route::get('items/sync/{id}/{fID}', 'ItemsController@syncByIDfID')->name('sync.byidfid');
            });

            Route::name('sertipikat.')->group(function() {
                Route::get('sertipikat', 'SertipikatController@index')->name('index');
                Route::get('sertipikat/data', 'SertipikatController@indexData')->name('index.data');
                Route::get('sertipikat/show', 'SertipikatController@show')->name('show');
                Route::get('sertipikat/sync', 'SertipikatController@sync')->name('sync');
                Route::get('sertipikat/sync-data', 'SertipikatController@syncDataNull')->name('sync.data');
                Route::get('sertipikat/export', 'SertipikatController@exportToExcel')->name('export');

                Route::get('sertipikat/search', 'SertipikatController@search')->name('search');
                Route::get('sertipikat/search/now', 'SertipikatController@searchNow')->name('search.now');
                Route::get('sertipikat/sync/now', 'SertipikatController@syncNow')->name('sync.now');
            });

            Route::name('warkah.')->group(function() {
                Route::get('warkah', 'WarkahController@index')->name('index');
                Route::get('warkah/data', 'WarkahController@indexData')->name('index.data');
                Route::get('warkah/show', 'WarkahController@show')->name('show');
                Route::get('warkah/sync', 'WarkahController@sync')->name('sync');
                Route::get('warkah/export', 'WarkahController@exportToExcel')->name('export');
            });

        });
    });
});

Entities/Sertipikat.php
<?php

namespace Modules\Mfiles\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;
use App\Models\User;

class Sertipikat extends Model
{
    use TraitsUuid;

    protected $table = 'mfl_sertipikat';

    public $incrementing    = false;

    protected $dates = [
        'tgl_buat',
        'tgl_akhir',
        'created',
        'last_modified',
    ];

    protected $fillable = [
        'index',
        'kode',
        'nomor',
        'tgl_buat',
        'tgl_akhir',
        'jenis',
        'tipe',
        'luas',
        'alamat',
        'pemegang_hak',
        'bus_unit',
        'doos',
        'rak',
        'bast',
        'sup_doc',
        'last_sync',
        'last_sync_by',
        'doc_id',
        'doc_title',
        'doc_version',
        'doc_type',
        'file_size',
        'file_ext',
        'created',
        'created_by',
        'last_modified',
        'last_modified_by'
    ];

    public function lastSyncBy()
    {
        return $this->belongsTo(User::class, 'last_sync_by')->withDefault([
            'name' => null
        ]);
    }
}

Http/Controllers/SertipikatController.php
<?php

namespace Modules\Mfiles\Http\Controllers;

use Exception;
use Carbon\Carbon;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use Modules\Mfiles\Entities\Sertipikat;
use Modules\Mfiles\Exports\DocumentSertipikatExportToExcel;
use Yajra\DataTables\Facades\DataTables;

class SertipikatController extends Controller
{
    protected $pageTitle;
    protected $baseUrl;
    protected $username;
    protected $password;
    protected $vaultID;

    protected $client;
    protected $headers;

    public function __construct()
    {
        $this->pageTitle = 'Sertipikat';
        $this->baseUrl      = config('mfiles.base_url');
        $this->username     = config('mfiles.username');
        $this->password     = config('mfiles.password');
        $this->vaultID      = config('mfiles.vault_id');

        $this->client       = new Client();
        $this->headers      = [
            'Accept'        => 'application/json',
            'X-Username'    => $this->username,
            'X-Password'    => $this->password,
            'X-Vault'       => $this->vaultID
        ];
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('mfiles::sertipikat.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {
            $data = new Sertipikat();
            $data = $data->orderBy('last_modified', 'desc');
            $data = $data->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('alamat', function($row) {
                    return capitalize(strtolower($row->alamat));
                })
                ->addColumn('action', function($row) {
                    $actionBtn = 
                    '
                        <div class="btn-group">
                            <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Action</span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                <li>
                                    <a href="#" onclick="showDetail(\''.$row->id.'\');return false;"><i class="fa fa-eye"></i> Detail</a>
                                </li>
                            </ul>
                        </div>
                    ';
                    return $actionBtn;
                })
                ->rawColumns([
                    'action', 'alamat'
                ])
                ->make(true);
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show(Request $request)
    {
        $params['title']    = $this->pageTitle;
        $params['data']     = Sertipikat::findOrFail($request->id);
        return view('mfiles::sertipikat.show', $params);
    }

    public function sync()
    {
        try {
            ini_set('memory_limit','256M');
            ini_set('max_execution_time','0');
            $endPoint   = $this->baseUrl . 'views/V101/L17/items?limit=20000';
            $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
            $result         = json_decode($response->getbody()->getContents(), true);
            
            foreach($result['Items'] as $item) {

                if($item['FolderContentItemType'] == 4) {
                    $data['docTitle']   = $item['ObjectVersion']['Title'];
                    $data['docLastModUtc']  = $item['ObjectVersion']['LastModifiedUtc'];
                    $data['docID']      = $docID        = $item['ObjectVersion']['ObjVer']['ID'];
                    $data['docVersion'] = $docVersion   = $item['ObjectVersion']['ObjVer']['Version'];
                    $data['docType']    = $docType      = $item['ObjectVersion']['ObjVer']['Type'];
                    $data['fileSize']   = $item['ObjectVersion']['Files'][0]['Size'];
                    $data['fileExt']    = $item['ObjectVersion']['Files'][0]['Extension'];

                    $data['docProperties']  = array_reduce($this->getDocumentProperties($docType, $docID, $docVersion), 'array_merge', []);

                    $pemegangHak = $data['docProperties']['namaPemegangHak'] != 'Lain-lain'? $data['docProperties']['namaPemegangHak'] : $data['docProperties']['namaPemilikAwal'];

                    $dataSrtp['doc_id']     = $data['docID'];
                    $dataSrtp['doc_title']  = $data['docTitle'];
                    $dataSrtp['doc_version']= $data['docVersion'];
                    $dataSrtp['doc_type']   = $data['docType'];
                    $dataSrtp['file_size']  = $data['fileSize'];
                    $dataSrtp['file_ext']   = $data['fileExt'];

                    $dataSrtp['index']      = $data['docProperties']['indexNumber'];
                    $dataSrtp['nomor']      = str_pad($data['docProperties']['nomorSertifikat'], 5, '0', STR_PAD_LEFT);
                    $dataSrtp['tgl_buat']   = dateFormatYmd($data['docProperties']['tanggalSertifikat']);
                    $dataSrtp['tgl_akhir']  = dateFormatYmd($data['docProperties']['tanggalValid']);
                    $dataSrtp['jenis']      = $data['docProperties']['jenisSertifikat'];
                    $dataSrtp['tipe']       = $data['docProperties']['tipeSertifikat'];
                    $dataSrtp['luas']       = cleanNominal($data['docProperties']['luas']);
                    $dataSrtp['alamat']     = capitalize($data['docProperties']['alamatObjek']);
                    $dataSrtp['pemegang_hak']= $pemegangHak;
                    $dataSrtp['bus_unit']   = $data['docProperties']['businessUnit'];
                    $dataSrtp['doos']       = $data['docProperties']['doos'];
                    $dataSrtp['rak']        = $data['docProperties']['rak'];
                    $dataSrtp['bast']       = $data['docProperties']['bAST'];
                    $dataSrtp['sup_doc']    = $data['docProperties']['supportingDocument'];
                    $dataSrtp['last_sync']  = Carbon::now();
                    $dataSrtp['last_sync_by']= Auth::user()->id;
                    $dataSrtp['created']    = dateFormatYmdHis($data['docProperties']['created']);
                    $dataSrtp['created_by'] = $data['docProperties']['createdBy'];
                    $dataSrtp['last_modified']= dateFormatYmdHis($data['docProperties']['lastModified']);
                    $dataSrtp['last_modified_by'] = $data['docProperties']['lastModifiedBy'];

                    $cekSrtpExist = Sertipikat::where('doc_id', $data['docID']);
                    if($cekSrtpExist->count() > 0) {
                        $lastModified = dateFormatYmdHis($data['docProperties']['lastModified']);
                        if($cekSrtpExist->where('last_modified', '!=', $lastModified)->count() > 0) {
                            $cekSrtpExist->update($dataSrtp);
                        }
                    } else {
                        Sertipikat::create($dataSrtp);
                    }
                }
            }

            return response()->json([
                'message' => trans('message.success_save')
            ]);
        
        } catch(Exception $e) {

            return response()->json([
                'message' => trans('message.error_save')
            ]);
        }
            
    }

    public function exportToExcel()
    {
        
        $data = Sertipikat::orderBy('last_modified', 'desc')->get();

        return Excel::download(new DocumentSertipikatExportToExcel($data), 'sertipikat_'.date('Y-m-d').'.xlsx');
        
    }

    private function getDocumentProperties($type, $id, $version) {
        $endPoint   = $this->baseUrl . 'objects/properties;' . $type . '/' . $id . '/' . $version;
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result     = json_decode($response->getbody()->getContents(), true);
        $resultArray= [];
        foreach($result[0] as $item) {
            $arrayData = array(
                camel_case($this->getPropertyDefDetail($item['PropertyDef'])) => $item['Value']['DisplayValue']
            );
            array_push($resultArray, $arrayData);
        }
        return array_merge($resultArray);
    }

    private function getPropertyDefDetail($id) {
        $endPoint   = $this->baseUrl . 'structure/properties/' . $id;
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        return $result['Name'];
    }

    public function syncDataNull()
    {
        ini_set('memory_limit','256M');
        ini_set('max_execution_time','0');

        $srtp = Sertipikat::where('doc_id', null)->get();

        foreach($srtp as $row) {
            
            $endPoint   = $this->baseUrl . 'objects.aspx?q=' . $row->doc_title;
            $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
            $result         = json_decode($response->getbody()->getContents(), true);
            
            if(count($result['Items']) > 0) {
                
                foreach(array_slice($result['Items'], 0, 1) as $item) {
                    
                    $data['docTitle']   = $item['Title'];
                    $data['docLastModUtc']  = $item['LastModifiedUtc'];
                    $data['docID']      = $docID        = $item['ObjVer']['ID'];
                    $data['docVersion'] = $docVersion   = $item['ObjVer']['Version'];

Resources/views/sertipikat/index.blade.php
@extends('mfiles::layouts.master')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        @can('mfiles-sertipikat-search')
                            <a class="btn btn-sm btn-default" onclick="showSearch(); return false;">
                                <i class="fa fa-search"></i> Search
                            </a>
                        @endcan
                        @can('mfiles-sertipikat-sync')
                            <a class="btn btn-sm btn-info" id="btn-sync">
                                <i class="fa fa-refresh"></i> Sync
                            </a>
                        @endcan
                        @can('mfiles-sertipikat-export')
                            <a class="btn btn-sm btn-success" href="{!! route('sertipikat.export') !!}">
                                <i class="fa fa-file-excel-o"></i> Export to Excel
                            </a>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 500px">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="grid-sertipikat" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="vertical-align: middle; width: 2%">#</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Jenis</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Tipe</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Nomor</th>
                                        <th class="text-center" style="vertical-align: middle;">Pemegang<br>Hak</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">Luas<br>(m<sup>2</sup>)</th>
                                        <th class="text-center" style="vertical-align: middle; width: 10%">Alamat</th>
                                        <th class="text-center" style="vertical-align: middle; width: 7%">Tgl.<br>Sertipikat</th>
                                        <th class="text-center" style="vertical-align: middle; width: 7%">Tgl.<br>Valid</th>
                                        <th class="text-center" style="vertical-align: middle; ">Business<br>Unit</th>
                                        <th class="text-center" style="vertical-align: middle; width: 80px">Modified</th>
                                        <th class="text-center" style="vertical-align: middle; width: 5%">
                                            <i class="fa fa-navicon"></i>
                                        </th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="form-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="detail">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div id="content"></div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            @can('mfiles-sertipikat-sync')
            $('#btn-sync').on('click', function(e) {
                $.ajax({
                    url: "{!! route('sertipikat.sync') !!}",
                    type: "GET",
                    success: function(data) {
                        toastr.success(data.message);
                        $('#grid-sertipikat').DataTable().ajax.reload(null, false);
                    },
                    error: function(error) {
                        toastr.error(error.message);
                    }
                });
            });
            @endcan

            var table = $('#grid-sertipikat').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload(null, false);
                        }
                    },
                ],
                ajax: { 
                    url: "{!! route('sertipikat.index.data') !!}",
                    pages: 10,
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'jenis', name: 'jenis', className: "small"},
                    {data: 'tipe', name: 'tipe', className: "small"},
                    {data: 'nomor', name: 'nomor', className: "small"},
                    {data: 'pemegang_hak', name: 'pemegang_hak', className: "small"},
                    {data: 'luas', name: 'luas', className: "small text-right"},
                    {data: 'alamat', name: 'alamat', className: "small"},
                    {data: 'tgl_buat', name: 'tgl_buat', className: "small"},
                    {data: 'tgl_akhir', name: 'tgl_akhir', className: "small"},
                    {data: 'bus_unit', name: 'bus_unit', className: "small"},
                    {data: 'updated_at', name: 'updated_at', className: "small"},
                    {data: 'action', name: 'action', className: "small text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 5, render: $.fn.dataTable.render.number( '.', ',', 0, '' )},
                    {targets: 7, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY' )},
                    {targets: 8, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY' )},
                    {targets: 10, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm' )},
                ],
                order: [
                    [10, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });
        });

        function showDetail(id) {
            $.ajax({
                type: "GET",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{!! route('sertipikat.show') !!}",
                data: {id: id},
                success: function(data) {
                    $('#form-modal').modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                    $('#content').html(data);
                }
            });
        }

        function showSearch() {
            $.ajax({
                type: "GET",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: "{!! route('sertipikat.search') !!}",
                success: function(data) {
                    $('#form-modal').modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                    $('#content').html(data);
                }
            });
        }

    </script>
@endsection

Resources/views/sertipikat/search-result.blade.php
<hr>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table id="grid-sertipikat-search" class="table table-bordered table-striped small" style="margin-top: 20px">
                <thead>
                    <tr>
                        <th class="text-center" style="vertical-align: middle; width: 2%">#</th>
                        <th class="text-center" style="vertical-align: middle; width: 5%">Jenis</th>
                        <th class="text-center" style="vertical-align: middle; width: 5%">Tipe</th>
                        <th class="text-center" style="vertical-align: middle; width: 5%">Nomor</th>
                        <th class="text-center" style="vertical-align: middle;">Pemegang<br>Hak</th>
                        <th class="text-center" style="vertical-align: middle; width: 5%">Luas<br>(m<sup>2</sup>)</th>
                        <th class="text-center" style="vertical-align: middle; width: 10%">Alamat</th>
                        <th class="text-center" style="vertical-align: middle; width: 7%">Tgl.<br>Sertipikat</th>
                        <th class="text-center" style="vertical-align: middle; width: 9%">Tgl.<br>Valid</th>
                        <th class="text-center" style="vertical-align: middle; ">Business<br>Unit</th>
                        <th class="text-center" style="vertical-align: middle; ">Dokumen<br>Title</th>
                        <th class="text-center" style="vertical-align: middle; width: 80px">Modified</th>
                        {{-- <th class="text-center" style="vertical-align: middle; width: 5%">
                            <i class="fa fa-navicon"></i>
                        </th> --}}
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $row)
                        <tr class="small">
                            <td>{!! $index++ !!}</td>
                            <td>{!! $row['jenis'] !!}</td>
                            <td>{!! $row['tipe'] !!}</td>
                            <td>{!! $row['nomor'] !!}</td>
                            <td>{!! $row['pemegang_hak'] !!}</td>
                            <td>{!! numberFormat($row['luas']) !!}</td>
                            <td>{!! $row['alamat'] !!}</td>
                            <td>{!! $row['tgl_buat'] !!}</td>
                            <td>{!! $row['tgl_akhir'] !!}</td>
                            <td>{!! $row['bus_unit'] !!}</td>
                            <td>{!! $row['doc_title'] !!}</td>
                            <td>{!! $row['last_modified'] !!}</td>
                            {{-- <td></td> --}}
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#grid-sertipikat-search').DataTable({
            ordering: false
        });
    });
</script>

Resources/views/sertipikat/search.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="detail">Search {!! $title !!} on M-Files</h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="q" class="col-sm-2 control-label">Title</label>
                <div class="col-sm-8">
                    {!! Form::text('q', null, [ 'class' => 'form-control', 'id' => 'q', 'autocomplete' => 'off']) !!}
                </div>
                <div class="col-sm-2">
                    <a class="btn btn-default" onclick="searchNow(); return false;">
                        <i class="fa fa-search"></i> Search
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="content-data"></div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-success" id="btn-sync-now" style="display: none" onclick="syncNow(); return false;"><i class="fa fa-refresh"></i> Sync</button>
</div>

<script type="text/javascript">
    $(document).ready(function() {

    });

    function searchNow() {
        var q = $('#q').val();
        $.ajax({
            type: "GET",
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: "{!! route('sertipikat.search.now') !!}",
            data: {q: q},
            success: function(data) {
                $('#content-data').html(data);
                $('#btn-sync-now').show();
            }
        });
    }

    function syncNow() {
        var q = $('#q').val();
        $.ajax({
            type: "GET",
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: "{!! route('sertipikat.sync.now') !!}",
            data: {q: q},
            success: function(data) {
                toastr.success(data.message);
                $('#grid-sertipikat').DataTable().ajax.reload(null, false);
            }
        });
    }
</script>