Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('m-files')->group(function() {
            
            Route::name('item.')->group(function() {
                Route::get('items/exports/{id}/{fID}', 'ItemsController@exportExcel')->name('byidfid.export');
                Route::get('items', 'ItemsController@index')->name('index');
                Route::get('items/{id}', 'ItemsController@getViewByID')->name('id');
                Route::get('items/object/{id}', 'ItemsController@getObjectByID')->name('object.byid');
                Route::get('items/prop/{id}', 'ItemsController@getPropertyDefDetail')->name('prop.id');
                Route::get('items/{id}/{fID}', 'ItemsController@getViewByIDfID')->name('byidfid');
                
                Route::get('items/sync/{id}/{fID}', 'ItemsController@syncByIDfID')->name('sync.byidfid');
            });

            Route::name('sertipikat.')->group(function() {
                Route::get('sertipikat', 'SertipikatController@index')->name('index');
                Route::get('sertipikat/data', 'SertipikatController@indexData')->name('index.data');
                Route::get('sertipikat/show', 'SertipikatController@show')->name('show');
                Route::get('sertipikat/sync', 'SertipikatController@sync')->name('sync');
                Route::get('sertipikat/sync-data', 'SertipikatController@syncDataNull')->name('sync.data');
                Route::get('sertipikat/export', 'SertipikatController@exportToExcel')->name('export');

                Route::get('sertipikat/search', 'SertipikatController@search')->name('search');
                Route::get('sertipikat/search/now', 'SertipikatController@searchNow')->name('search.now');
                Route::get('sertipikat/sync/now', 'SertipikatController@syncNow')->name('sync.now');
            });

            Route::name('warkah.')->group(function() {
                Route::get('warkah', 'WarkahController@index')->name('index');
                Route::get('warkah/data', 'WarkahController@indexData')->name('index.data');
                Route::get('warkah/show', 'WarkahController@show')->name('show');
                Route::get('warkah/sync', 'WarkahController@sync')->name('sync');
                Route::get('warkah/export', 'WarkahController@exportToExcel')->name('export');
            });

        });
    });
});

Http/Controllers/ItemsController.php
<?php

namespace Modules\Mfiles\Http\Controllers;

use Excel;
use Carbon\Carbon;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Stream;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\Mfiles\Entities\Sertipikat;
use Modules\Mfiles\Exports\DocumentSertipikatExport;
use Modules\Mfiles\Exports\DocumentSertipikatExportToExcel;

class ItemsController extends Controller
{
    protected $pageTitle;
    protected $baseUrl;
    protected $username;
    protected $password;
    protected $vaultID;

    protected $client;
    protected $headers;

    public function __construct()
    {
        $this->pageTitle    = 'M-Files';
        $this->baseUrl      = config('mfiles.base_url');
        $this->username     = config('mfiles.username');
        $this->password     = config('mfiles.password');
        $this->vaultID      = config('mfiles.vault_id');

        $this->client       = new Client();
        $this->headers      = [
            'Accept'        => 'application/json',
            'X-Username'    => $this->username,
            'X-Password'    => $this->password,
            'X-Vault'       => $this->vaultID
        ];
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index() {
        $params['pageTitle']    = $this->pageTitle;
        $endPoint       = $this->baseUrl . 'views/items.aspx';
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $params['data'] = $result['Items'];
        return view('mfiles::items.index', $params);
    }

    /**
     * Get View By ID
     * @param int $id
     * @return Response
     * @endpoint http://jbmfiles01/REST/views/V{id}/items.aspx 
     */
    public function getViewByID($id) {
        $params['pageTitle']    = $this->pageTitle;
        $endPoint       = $this->baseUrl . 'views/V' . $id . '/items.aspx';
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $params['data'] = $result['Items'];
        $params['path'] = $result['Path'];
        return view('mfiles::items.items-by-id', $params);
    }

    /* http://jbmfiles01/REST/views/V{id}/{fID}/items.aspx */
    public function getViewByIDfID($id, $fID) {
        $params['pageTitle']    = $this->pageTitle;
        $endPoint       = $this->baseUrl . 'views/' . $id . '/L' . $fID . '/items?limit=10000';
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers, 'stream' => false]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $params['data'] = $result['Items'];
        return view('mfiles::items.items-by-id-fid', $params);
    }

    public function getObjectByID($id) {
        $params['pageTitle']    = $this->pageTitle;
        $endPoint       = $this->baseUrl . 'objects/0/' . $id . '/latest/properties';
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $params['data'] = $result;
        return view('mfiles::items.document-by-id', $params);
    }

    public function getDocumentProperty($id = 'V101', $fID = '17') {
        /* Get Data Sertifikat */
        $endPoint   = $this->baseUrl . 'views/' . $id . '/L' . $fID . '/items?limit=10000';
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $resultArray = [];
        foreach($result['Items'] as $item) {
            if($item['FolderContentItemType'] == 4) {
                $data['docTitle']   = $item['ObjectVersion']['Title'];
                $data['docLastModUtc']  = $item['ObjectVersion']['LastModifiedUtc'];
                $data['docID']      = $docID        = $item['ObjectVersion']['ObjVer']['ID'];
                $data['docVersion'] = $docVersion   = $item['ObjectVersion']['ObjVer']['Version'];
                $data['docType']    = $docType      = $item['ObjectVersion']['ObjVer']['Type'];
                $data['fileSize']   = $item['ObjectVersion']['Files'][0]['Size'];
                $data['fileExt']    = $item['ObjectVersion']['Files'][0]['Extension'];

                $data['docProperties']  = array_reduce($this->getDocumentProperties($docType, $docID, $docVersion), 'array_merge', []);
                array_push($resultArray, $data);
            }
        }
        $params['pageTitle']    = $this->pageTitle;
        $params['data'] = $resultArray;
        return view('mfiles::items.export', $params);
    }

    public function getPropertyDefDetail($id) {
        $endPoint   = $this->baseUrl . 'structure/properties/' . $id;
        $response       = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        return $result['Name'];
    }

    private function getDocumentProperties($type, $id, $version) {
        $endPoint   = $this->baseUrl . 'objects/properties;' . $type . '/' . $id . '/' . $version;
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result     = json_decode($response->getbody()->getContents(), true);
        $resultArray= [];
        foreach($result[0] as $item) {
            $arrayData = array(
                camel_case($this->getPropertyDefDetail($item['PropertyDef'])) => $item['Value']['DisplayValue']
            );
            array_push($resultArray, $arrayData);
        }
        return array_merge($resultArray);
    }

    /**
     * Export from M-Files to Excel directly
     */
    public function exportExcel($id = 'V101', $fID = '17')
    {
        ini_set('memory_limit','256M');
        ini_set('max_execution_time','0');
        $endPoint   = $this->baseUrl . 'views/' . $id . '/L' . $fID . '/items?limit=10000';
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        $resultArray = [];
        foreach($result['Items'] as $item) {
            if($item['FolderContentItemType'] == 4) {
                $data['docTitle']   = $item['ObjectVersion']['Title'];
                $data['docLastModUtc']  = $item['ObjectVersion']['LastModifiedUtc'];
                $data['docID']      = $docID        = $item['ObjectVersion']['ObjVer']['ID'];
                $data['docVersion'] = $docVersion   = $item['ObjectVersion']['ObjVer']['Version'];
                $data['docType']    = $docType      = $item['ObjectVersion']['ObjVer']['Type'];
                $data['fileSize']   = $item['ObjectVersion']['Files'][0]['Size'];
                $data['fileExt']    = $item['ObjectVersion']['Files'][0]['Extension'];

                $data['docProperties']  = array_reduce($this->getDocumentProperties($docType, $docID, $docVersion), 'array_merge', []);
                array_push($resultArray, $data);
            }
        }
        return Excel::download(new DocumentSertipikatExport($resultArray), 'sertipikat_'.date('Y-m-d').'.xlsx');
    }

    /**
     * Export from M-Files to Excel with sync to local database
     */
    public function syncByIDfID($id = 'V101', $fID = '17')
    {
        ini_set('memory_limit','256M');
        ini_set('max_execution_time','0');
        $endPoint   = $this->baseUrl . 'views/' . $id . '/L' . $fID . '/items?limit=1000';
        $response   = $this->client->request('GET', $endPoint, [ 'headers' => $this->headers]);
        $result         = json_decode($response->getbody()->getContents(), true);
        
        foreach($result['Items'] as $item) {
            if($item['FolderContentItemType'] == 4) {
                $data['docTitle']   = $item['ObjectVersion']['Title'];
                $data['docLastModUtc']  = $item['ObjectVersion']['LastModifiedUtc'];
                $data['docID']      = $docID        = $item['ObjectVersion']['ObjVer']['ID'];
                $data['docVersion'] = $docVersion   = $item['ObjectVersion']['ObjVer']['Version'];
                $data['docType']    = $docType      = $item['ObjectVersion']['ObjVer']['Type'];
                $data['fileSize']   = $item['ObjectVersion']['Files'][0]['Size'];
                $data['fileExt']    = $item['ObjectVersion']['Files'][0]['Extension'];

                $data['docProperties']  = array_reduce($this->getDocumentProperties($docType, $docID, $docVersion), 'array_merge', []);

                $pemegangHak = $data['docProperties']['namaPemegangHak'] != 'Lain-lain'? $data['docProperties']['namaPemegangHak'] : $data['docProperties']['namaPemilikAwal'];

                $dataSrtp['doc_id']     = $data['docID'];
                $dataSrtp['doc_title']  = $data['docTitle'];
                $dataSrtp['doc_version']= $data['docVersion'];
                $dataSrtp['doc_type']   = $data['docType'];
                $dataSrtp['file_size']  = $data['fileSize'];
                $dataSrtp['file_ext']   = $data['fileExt'];

                $dataSrtp['index']      = $data['docProperties']['indexNumber'];
                $dataSrtp['nomor']      = str_pad($data['docProperties']['nomorSertifikat'], 5, '0', STR_PAD_LEFT);
                $dataSrtp['tgl_buat']   = dateFormatYmd($data['docProperties']['tanggalSertifikat']);
                $dataSrtp['tgl_akhir']  = dateFormatYmd($data['docProperties']['tanggalValid']);
                $dataSrtp['jenis']      = $data['docProperties']['jenisSertifikat'];
                $dataSrtp['tipe']       = $data['docProperties']['tipeSertifikat'];

Resources/views/items/document-by-id.blade.php
@extends('mfiles::layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Detail <b>{!! __getDetailPropertyDef($data, 1101, 1) !!}</b></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-danger" href="{!! URL::previous() !!}">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <table id="grid-items" class="table table-bordered table-striped">
                    <tr>
                        <th width="40%">Class</th>
                        <td>{!! __getDetailPropertyDef($data, 100, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Nama</th>
                        <td>{!! __getDetailPropertyDef($data, 1101, 1) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Nomor Sertifikat</th>
                        <td>{!! __getDetailPropertyDef($data, 1102, 1) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Tgl. Sertifikat</th>
                        <td>{!! __getDetailPropertyDef($data, 1103, 5) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Tipe Sertifikat</th>
                        <td>{!! __getDetailPropertyDef($data, 1108, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Jenis Sertifikat</th>
                        <td>{!! __getDetailPropertyDef($data, 1105, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">BAST</th>
                        <td>{!! __getDetailPropertyDef($data, 1113, 1) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Alamat Objek</th>
                        <td>{!! __getDetailPropertyDef($data, 1068, 13) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Nama Pemegang Hak</th>
                        <td>{!! __getDetailPropertyDef($data, 1126, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Business Unit</th>
                        <td>{!! __getDetailPropertyDef($data, 1152, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Tgl. Valid</th>
                        <td>{!! __getDetailPropertyDef($data, 1106, 5) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Luas</th>
                        <td>{!! __getDetailPropertyDef($data, 1097, 1) !!} <small>m<sup>2</sup></small></td>
                    </tr>
                    <tr>
                        <th width="">Doos</th>
                        <td>{!! __getDetailPropertyDef($data, 1111, 1) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Rak</th>
                        <td>{!! __getDetailPropertyDef($data, 1124, 9) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Supporting Document</th>
                        <td>{!! __getDetailPropertyDef($data, 1051, 10) !!}</td>
                    </tr>
                    <tr>
                        <th width="">Created By</th>
                        <td>
                            {!! __getDetailPropertyDef($data, 25, 9) !!}
                            <small>({!! __getDetailPropertyDef($data, 20, 7) !!})</small>
                        </td>
                    </tr>
                    <tr>
                        <th width="">Last Modified By</th>
                        <td>
                            {!! __getDetailPropertyDef($data, 23, 9) !!}
                            <small>({!! __getDetailPropertyDef($data, 21, 7) !!})</small>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

Resources/views/items/export.blade.php
@extends('mfiles::layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-danger" href="{!! URL::previous() !!}">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <table id="grid-items" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 5%">No.</th>
                            <th>Name</th>
                            <th style="width: 80px">Alamat</th>
                            <th style="width: 100px">Date Modified</th>
                        </tr>
                    </thead>
                    <tbody class="small">
                        @foreach ($data as $items)
                            {{-- @foreach ($items['docProperties'] as $item) --}}
                            {{-- {!! dd($item['nameOrTitle']) !!} --}}
                            <tr>
                                <td></td>
                                <td>
                                    {!! $items['docProperties']['nameOrTitle'] !!}
                                </td>
                                <td class="text-right">
                                    {!! $items['docProperties']['alamatObjek'] !!}
                                </td>
                                <td class="text-right">
                                    {{-- {!! $items['docProperties'][10]['alamatObjek'] !!} --}}
                                    {{-- @php
                                        setLocale(LC_TIME, 'id');
                                        $utc = Carbon::parse($items->docLastModUtc)->setTimezone('UTC');
                                        $idTz= Carbon::createFromFormat('Y-m-d H:i:s', $utc, 'UTC');
                                    @endphp
                                    {!! $idTz->setTimezone('Asia/Jakarta')->format('d-M-Y H:i:s') !!} --}}
                                </td>
                            </tr>
                            {{-- @endforeach --}}
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-items").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 2, "orderable": false},
                ],
                "order": [[3, 'asc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection

Resources/views/items/index.blade.php
@extends('mfiles::layouts.master')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right"></div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <table id="grid-items" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">No.</th>
                                <th>Name</th>
                                <th>Type</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            @foreach ($data as $items)
                            <tr>
                                <td></td>
                                <td>
                                    <a href="{!! route('item.id', $items['View']['ID']) !!}">
                                        {!! $items['View']['Name'] !!}
                                    </a>
                                </td>
                                <td>
                                    {!! $items['FolderContentItemType'] == 1 ? 'View' : null !!}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-items").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 2, "orderable": false},
                ],
                "order": [[1, 'asc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection

Resources/views/items/items-by-id-fid.blade.php
@extends('mfiles::layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-success" href="{!! route('item.sync.byidfid', [Request()->segment(4), Request()->segment(5)]) !!}">
                        <i class="fa fa-file-excel-o"></i> Excel
                    </a>
                    {{-- <a class="btn btn-sm btn-danger" href="{!! URL::previous() !!}">
                        <i class="fa fa-times"></i>
                    </a> --}}
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <table id="grid-items" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 5%">No.</th>
                            <th>Name</th>
                            <th style="width: 80px">Size</th>
                            <th style="width: 100px">Date Modified</th>
                        </tr>
                    </thead>
                    <tbody class="small">
                        @foreach ($data as $items)
                        <tr>
                            <td></td>
                            <td>
                                @if($items['FolderContentItemType'] == 4)
                                    <a href="{!! route('item.object.byid', $items['ObjectVersion']['DisplayID']) !!}" title="View">
                                        {!! $items['ObjectVersion']['Title'] !!}
                                    </a>
                                {{-- @elseif($items['FolderContentItemType'] == 2)
                                    <a href="{!! route('view.byidfid', [$path, $items['PropertyFolder']['SerializedValue']]) !!}" title="Virtual Folder">
                                        {!! $items['PropertyFolder']['DisplayValue'] !!}
                                    </a> --}}
                                @endif
                            </td>
                            <td class="text-right">
                                {!! formatSizeUnits($items['ObjectVersion']['Files'][0]['Size']) !!}
                            </td>
                            <td class="text-right">
                                @php
                                    setLocale(LC_TIME, 'id');
                                    $utc = Carbon::parse($items['ObjectVersion']['LastModified'])->setTimezone('UTC');
                                    $idTz= Carbon::createFromFormat('Y-m-d H:i:s', $utc, 'UTC');
                                @endphp
                                {!! $idTz->setTimezone('Asia/Jakarta')->format('d-M-Y H:i:s') !!}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-items").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 2, "orderable": false},
                ],
                "order": [[3, 'asc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection

Resources/views/items/items-by-id.blade.php
@extends('mfiles::layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-danger" href="{!! route('item.index') !!}">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <table id="grid-items" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width: 5%">No.</th>
                            <th>Name</th>
                            <th>Type</th>
                        </tr>
                    </thead>
                    <tbody class="small">
                        @foreach ($data as $items)
                        <tr>
                            <td></td>
                            <td>
                                @if($items['FolderContentItemType'] == 1)
                                <a href="{!! route('item.id', $items['View']['ID']) !!}">
                                    {!! $items['View']['Name'] !!}
                                </a>
                                @elseif($items['FolderContentItemType'] == 2)
                                <a href="{!! route('item.byidfid', [ substr($path,1), $items['PropertyFolder']['SerializedValue']]) !!}" title="Virtual Folder">
                                    {!! $items['PropertyFolder']['DisplayValue'] !!}
                                </a>
                                @endif
                            </td>
                            <td>
                                @if($items['FolderContentItemType'] == 1)
                                View
                                @elseif($items['FolderContentItemType'] == 2)
                                Virtual Folder
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function(){
            var t = $("#grid-items").DataTable({
                "columnDefs": [ 
                    {
                        "targets": 0,
                        "searchable": false,
                        "orderable": false,
                        "className": "dt-body-center",
                    },
                    {"targets": 2, "orderable": false},
                ],
                "order": [[1, 'asc']],
            });

            t.on('order.dt search.dt', function() {
                t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function(cell, i) {
                    cell.innerHTML = i+1;
                });
            }).draw();
        });
    </script>
@endsection